### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marthieu**
Change `Share` to `Sync`(see https://github.com/mrmonday/rust/commit/8f1b4f0305007f53714d4212885dc9598f49664f).
Add a "Getting Started" section.

### CODE REVIEW

**Comment by Kimundi** [comment]
Hi, thanks for this contribution! Regarding the two dependency variations: Maybe it would make sense to make the package dependency to be something like `lazy_static = "0.*"` instead, to not break the instruction with every update?

**Comment by marthieu** [comment]
Ok, I edited the commit to address this.
Let me know what you think.

**Comment by Kimundi** [comment]
Actually, I meant to use the actual string `"0.*"` - semver supports wildcards, so that kind of dependency would match any version of this package less than `1.0.0`.

However, reading up a bit on semver, it seems like using something like `"0.1.*"` would be more appropriate, because that allows for any update of this package that does not change its API.

The idea here being that the README contains a cargo dependency line that can be copied directly, and that will do the right thing even if I have to release new versions due to compiler changes :)

**Comment by Kimundi** [comment]
Yeah, its kinda hidden away, I only found it because I happened to know it was supported.

Anyway, I'm happy with the text now, thanks for your contribution! :)

**Pull request merged**
